# 1. Data Loading

- **Reproducibility**: Setting up robust paths ensures the notebook works across different machines and environments
- **Quick Validation**: Initial checks help identify data issues early in the analysis pipeline
- **Understanding Schema**: Creating a data dictionary provides immediate insight into column structure and data quality
- **Error Prevention**: Proper path handling prevents common file not found errors
- **Scalability**: Modular approach makes it easy to add more data sources later
- **Documentation**: Clear markdown cells explain the purpose and methodology for future reference
- **Quality Assurance**: Systematic checks ensure data integrity before proceeding to analysis

In [13]:
import pandas as pd
import numpy as np
from pathlib import Path

# Set up project paths robustly
PROJECT_ROOT = Path.cwd().parent  # Go up from /notebooks to repo root
RAW_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
VISUALS_DIR = PROJECT_ROOT / "visuals"

# Create missing directories
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
VISUALS_DIR.mkdir(parents=True, exist_ok=True)

print("Project paths resolved:")
print(f"PROJECT_ROOT: {PROJECT_ROOT}")
print(f"RAW_DIR: {RAW_DIR}")
print(f"PROCESSED_DIR: {PROCESSED_DIR}")
print(f"VISUALS_DIR: {VISUALS_DIR}")

Project paths resolved:
PROJECT_ROOT: c:\Users\shiva\OneDrive\Desktop\projects\cancer-analysis
RAW_DIR: c:\Users\shiva\OneDrive\Desktop\projects\cancer-analysis\data\raw
PROCESSED_DIR: c:\Users\shiva\OneDrive\Desktop\projects\cancer-analysis\data\processed
VISUALS_DIR: c:\Users\shiva\OneDrive\Desktop\projects\cancer-analysis\visuals

In [14]:
# List available data files
if not RAW_DIR.exists():
    raise FileNotFoundError(f"Raw data directory not found: {RAW_DIR}")

# Find CSV and Excel files
csv_files = list(RAW_DIR.glob("*.csv"))
excel_files = list(RAW_DIR.glob("*.xlsx"))
all_files = csv_files + excel_files

if not all_files:
    raise FileNotFoundError(f"No CSV or Excel files found in {RAW_DIR}")

print(f"Found {len(all_files)} data file(s):")
for i, file in enumerate(all_files, 1):
    print(f"  {i}. {file.name}")

# Select the first CSV by default (easy to change)
if csv_files:
    DATA_PATH = csv_files[0]
else:
    DATA_PATH = excel_files[0]

print(f"\nChosen file: {DATA_PATH.name}")
print(f"Full path: {DATA_PATH}")

Found 1 data file(s):
  1. United States Cancer Statistics, 2018-2023 Mortality Single race.csv

Chosen file: United States Cancer Statistics, 2018-2023 Mortality Single race.csv
Full path: c:\Users\shiva\OneDrive\Desktop\projects\cancer-analysis\data\raw\United States Cancer Statistics, 2018-2023 Mortality Single race.csv

In [15]:
# Load the dataset
if DATA_PATH.suffix.lower() == '.csv':
    df = pd.read_csv(DATA_PATH, low_memory=False)
elif DATA_PATH.suffix.lower() in ['.xlsx', '.xls']:
    df = pd.read_excel(DATA_PATH)
else:
    raise ValueError(f"Unsupported file format: {DATA_PATH.suffix}")

print(f"Dataset loaded successfully!")
print(f"Shape: {df.shape[0]:,} rows × {df.shape[1]} columns")

Dataset loaded successfully!
Shape: 46 rows × 7 columns

## Quick Sanity Checks

In [16]:
print("=== First 5 rows ===")
display(df.head(5))

print("\n=== Last 5 rows ===")
display(df.tail(5))

if len(df) >= 5:
    print("\n=== Random sample of 5 rows ===")
    display(df.sample(5, random_state=42))

print("\n=== DataFrame Info ===")
df.info()

print("\n=== Descriptive Statistics ===")
# Limit output if there are many columns
max_cols_to_show = 30
if df.shape[1] <= max_cols_to_show:
    display(df.describe(include="all").T)
else:
    print(f"Showing first {max_cols_to_show} columns (out of {df.shape[1]}):")
    display(df.describe(include="all").T.head(max_cols_to_show))

=== First 5 rows ===

  Notes    Year  Year Code  Deaths  Population  Age-Adjusted Rate  Crude Rate
0   NaN  2018.0     2018.0  1841.0  81956393.0                2.2         2.2
1   NaN  2019.0     2019.0  1704.0  81679568.0                2.1         2.1
2   NaN  2020.0     2020.0  1702.0  82873432.0                2.0         2.1
3   NaN  2021.0     2021.0  1722.0  82201873.0                2.1         2.1
4   NaN  2022.0     2022.0  1772.0  81903660.0                2.1         2.2

=== Last 5 rows ===

,Notes,Year,Year Code,Deaths,Population,Age-Adjusted Rate,Crude Rate
41,of persons of unknown age are not included in ...,NaN,NaN,NaN,NaN,NaN,NaN
42,persons of unknown age are included. </li></ul>,NaN,NaN,NaN,NaN,NaN,NaN
43,2. Because the vast majority of Kaposi sarcoma...,NaN,NaN,NaN,NaN,NaN,NaN
44,infection and acquired immunodeficiency syndro...,NaN,NaN,NaN,NaN,NaN,NaN
45,death counts have been moved to the Miscellane...,NaN,NaN,NaN,NaN,NaN,NaN

=== Random sample of 5 rows ===

,Notes,Year,Year Code,Deaths,Population,Age-Adjusted Rate,Crude Rate
39,calculating age-adjusted incidence and death r...,NaN,NaN,NaN,NaN,NaN,NaN
25,---,NaN,NaN,NaN,NaN,NaN,NaN
26,Caveats:,NaN,NaN,NaN,NaN,NaN,NaN
44,infection and acquired immunodeficiency syndro...,NaN,NaN,NaN,NaN,NaN,NaN
35,condition. </li><li> The population used to ag...,NaN,NaN,NaN,NaN,NaN,NaN

=== DataFrame Info ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Notes              40 non-null     object
 1   Year               6 non-null      float64
 2   Year Code          6 non-null      float64
 3   Deaths             6 non-null      float64
 4   Population         6 non-null      float64
 5   Age-Adjusted Rate  6 non-null      float64
 6   Crude Rate         6 non-null      float64
dtypes: float64(6), object(1)
memory usage: 2.6+ KB

=== Descriptive Statistics ===

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Notes,40,36,---,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Year,6.0,NaN,NaN,NaN,2020.5,1.870829,2018.0,2019.25,2020.5,2021.75,2023.0
Year Code,6.0,NaN,NaN,NaN,2020.5,1.870829,2018.0,2019.25,2020.5,2021.75,2023.0
Deaths,6.0,NaN,NaN,NaN,1761.666667,62.278942,1702.0,1708.5,1747.0,1814.75,1841.0
Population,6.0,NaN,NaN,NaN,82031481.166667,467559.332239,81573961.0,81735591.0,81930026.5,82140503.0,82873432.0
Age-Adjusted Rate,6.0,NaN,NaN,NaN,2.116667,0.075277,2.0,2.1,2.1,2.175,2.2
Crude Rate,6.0,NaN,NaN,NaN,2.15,0.054772,2.1,2.1,2.15,2.2,2.2

## Data Quality Snapshot

In [17]:
# Missing values analysis
missing_counts = df.isnull().sum()
missing_percentages = (missing_counts / len(df)) * 100
missing_df = pd.DataFrame({
    'missing_count': missing_counts,
    'missing_pct': missing_percentages
}).sort_values('missing_count', ascending=False)

print("=== Missing Values ===")
display(missing_df[missing_df['missing_count'] > 0])

# Duplicate rows
duplicate_count = df.duplicated().sum()
print(f"\n=== Duplicate Rows ===")
print(f"Number of duplicate rows: {duplicate_count:,}")
print(f"Percentage of duplicates: {(duplicate_count / len(df)) * 100:.2f}%")

# Unique values per column
unique_counts = df.nunique()
print(f"\n=== Unique Values per Column ===")
# Show top 25 columns by uniqueness if there are many columns
if len(unique_counts) > 25:
    print("Showing top 25 columns by number of unique values:")
    display(unique_counts.sort_values(ascending=False).head(25))
else:
    display(unique_counts.sort_values(ascending=False))

# Memory usage
memory_mb = df.memory_usage(deep=True).sum() / 1024**2
print(f"\n=== Memory Usage ===")
print(f"Total memory usage: {memory_mb:.2f} MB")

=== Missing Values ===

                   missing_count  missing_pct
Year                          40    86.956522
Year Code                     40    86.956522
Deaths                        40    86.956522
Age-Adjusted Rate             40    86.956522
Population                    40    86.956522
Crude Rate                    40    86.956522
Notes                          6    13.043478

=== Duplicate Rows ===
Number of duplicate rows: 4
Percentage of duplicates: 8.70%

=== Unique Values per Column ===

Notes                36
Year                  6
Year Code             6
Deaths                6
Population            6
Age-Adjusted Rate     3
Crude Rate            2
dtype: int64

=== Memory Usage ===
Total memory usage: 0.01 MB

In [18]:
# Create data dictionary
schema_data = []
for col in df.columns:
    col_data = {
        'column_name': col,
        'dtype': str(df[col].dtype),
        'non_null_count': df[col].count(),
        'null_count': df[col].isnull().sum(),
        'null_pct': (df[col].isnull().sum() / len(df)) * 100,
        'n_unique': df[col].nunique()
    }
    schema_data.append(col_data)

schema_df = pd.DataFrame(schema_data)

print("=== Data Dictionary ===")
display(schema_df.sort_values('null_pct', ascending=False))

=== Data Dictionary ===

         column_name    dtype  non_null_count  null_count   null_pct  n_unique
1               Year  float64               6          40  86.956522         6
2          Year Code  float64               6          40  86.956522         6
3             Deaths  float64               6          40  86.956522         6
5  Age-Adjusted Rate  float64               6          40  86.956522         3
4         Population  float64               6          40  86.956522         6
6         Crude Rate  float64               6          40  86.956522         2
0              Notes   object              40           6  13.043478        36

## Notes / Next Steps

- **Next notebook section** will handle cleaning (missing values strategy, type conversions, normalization)
- **We will save a processed dataset** to `data/processed` later after cleaning transformations
- **Reproducibility**: All paths are set up relative to project root, making the notebook portable
- **Version control**: Consider committing the raw data dictionary to track schema changes over time
- **Data quality**: Review the missing values and duplicates before proceeding to cleaning steps