# 2. Basic Data Exploration

Simple pandas operations to understand the cancer mortality dataset.

In [11]:
import pandas as pd
import numpy as np
from pathlib import Path

# Set up paths
PROJECT_ROOT = Path.cwd().parent
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
RAW_DIR = PROJECT_ROOT / "data" / "raw"

print("Environment setup complete!")

Environment setup complete!

In [12]:
# Load data
cleaned_file = PROCESSED_DIR / "cleaned_cancer_data.csv"
raw_files = list(RAW_DIR.glob("*.csv"))

if cleaned_file.exists():
    df = pd.read_csv(cleaned_file)
    print(f"Loaded cleaned data: {df.shape[0]:,} rows × {df.shape[1]} columns")
elif raw_files:
    df = pd.read_csv(raw_files[0], low_memory=False)
    print(f"Loaded raw data: {df.shape[0]:,} rows × {df.shape[1]} columns")
else:
    raise FileNotFoundError("No data files found")

Loaded cleaned data: 6 rows × 7 columns

## Basic Data Information

In [3]:
# Display basic information
print("=== DataFrame Shape ===")
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]}")

print("\n=== Column Names ===")
print(df.columns.tolist())

=== DataFrame Shape ===
Rows: 6
Columns: 7

=== Column Names ===
['Notes', 'Year', 'Year Code', 'Deaths', 'Population', 'Age-Adjusted Rate', 'Crude Rate']

In [4]:
# Display first few rows
print("=== First 5 Rows ===")
df.head()

=== First 5 Rows ===

   Notes    Year  Year Code  Deaths  Population  Age-Adjusted Rate  Crude Rate
0    NaN  2018.0     2018.0  1841.0  81956393.0                2.2         2.2
1    NaN  2019.0     2019.0  1704.0  81679568.0                2.1         2.1
2    NaN  2020.0     2020.0  1702.0  82873432.0                2.0         2.1
3    NaN  2021.0     2021.0  1722.0  82201873.0                2.1         2.1
4    NaN  2022.0     2022.0  1772.0  81903660.0                2.1         2.2

In [5]:
# Display last few rows
print("=== Last 5 Rows ===")
df.tail()

=== Last 5 Rows ===

   Notes    Year  Year Code  Deaths  Population  Age-Adjusted Rate  Crude Rate
1    NaN  2019.0     2019.0  1704.0  81679568.0                2.1         2.1
2    NaN  2020.0     2020.0  1702.0  82873432.0                2.0         2.1
3    NaN  2021.0     2021.0  1722.0  82201873.0                2.1         2.1
4    NaN  2022.0     2022.0  1772.0  81903660.0                2.1         2.2
5    NaN  2023.0     2023.0  1829.0  81573961.0                2.2         2.2

In [6]:
# DataFrame info
print("=== DataFrame Info ===")
df.info()

=== DataFrame Info ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Notes              0 non-null      float64
 1   Year               6 non-null      float64
 2   Year Code          6 non-null      float64
 3   Deaths             6 non-null      float64
 4   Population         6 non-null      float64
 5   Age-Adjusted Rate  6 non-null      float64
 6   Crude Rate         6 non-null      float64
dtypes: float64(7)
memory usage: 468.0 bytes

In [7]:
# Data types
print("=== Data Types ===")
print(df.dtypes)

=== Data Types ===
Notes                float64
Year                 float64
Year Code            float64
Deaths               float64
Population           float64
Age-Adjusted Rate    float64
Crude Rate           float64
dtype: object

In [8]:
# Basic statistics
print("=== Descriptive Statistics ===")
df.describe()

=== Descriptive Statistics ===

,Notes,Year,Year Code,Deaths,Population,Age-Adjusted Rate,Crude Rate
count,0.0,6.000000,6.000000,6.000000,6.000000e+00,6.000000,6.000000
mean,NaN,2020.500000,2020.500000,1761.666667,8.203148e+07,2.116667,2.150000
std,NaN,1.870829,1.870829,62.278942,4.675593e+05,0.075277,0.054772
min,NaN,2018.000000,2018.000000,1702.000000,8.157396e+07,2.000000,2.100000
25%,NaN,2019.250000,2019.250000,1708.500000,8.173559e+07,2.100000,2.100000
50%,NaN,2020.500000,2020.500000,1747.000000,8.193003e+07,2.100000,2.150000
75%,NaN,2021.750000,2021.750000,1814.750000,8.214050e+07,2.175000,2.200000
max,NaN,2023.000000,2023.000000,1841.000000,8.287343e+07,2.200000,2.200000

In [9]:
# Missing values
print("=== Missing Values ===")
missing = df.isnull().sum()
print(missing[missing > 0] if missing.sum() > 0 else "No missing values")

=== Missing Values ===
Notes    6
dtype: int64

In [10]:
# Unique values per column
print("=== Unique Values per Column ===")
print(df.nunique())

=== Unique Values per Column ===
Notes                0
Year                 6
Year Code            6
Deaths               6
Population           6
Age-Adjusted Rate    3
Crude Rate           2
dtype: int64